import './globals.css'
import { Inter } from 'next/font/google'
import { bodyText, titleText } from './fonts'
import Header from '@/components/layout/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bodyText.variable} ${titleText.variable} bg-zinc-100 box-border` }>
      <body className={inter.className}>
        <Header />
        {children}
        </body>
    </html>
  )
}
